#This would be manually triggered by RC Manager
name: Update Release Tag
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag version(SEMVER)'
        required: true
        
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code, referencing to release branch
        with:
          ref: release/${{ inputs.tag_name }}
          fetch-depth: 0
        uses: actions/checkout@v3

      - name: config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update Tag
        uses: jimeh/update-tags-action@v1
        with:
          tags: release-${{ inputs.tag_name }}
          ref: release/${{ inputs.tag_name }}
          # github_token: ${{ secrets.ADMIN_PAT }}
      # - name: echo
      #   run: echo ${{ secrets.ADMIN_PAT }}