#This would be manually triggered by RC Manager
name: Update Release Tag
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag version(SEMVER)'
        required: true
        
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - name: Update Tag
        uses: jimeh/update-tags-action@v1
        with:
          tags: release-${{ inputs.tag_name }}
          ref: release/${{ inputs.tag_name }}